### PR TITLE
Pump to GG version 1.9.1

### PR DESCRIPTION
**Pull request by xmariopereira**

### CODE REVIEW

**Comment by xmariopereira** [comment]
already signed CLA

**Comment by markpeek** [comment]
@mariopoeta thank you for the PR. Right now your signed-off is the git commit subject. Could you try doing this:
```git commit --amend```
Update the commit message to:
```
Bump to Greengrass 1.9.1

Signed-off-by: Mario Pereira <mario.pereira@outlook.pt>
```
And then push the changes again? Likely need to add -f for that branch. Thanks.

**Comment by xmariopereira** [comment]
added in commit 5a7b3a3

by the way, do you know who is maintaining the ansible-greengrass role? i created PR it for too.

**Comment by xmariopereira** [comment]
p.s I am sorry for all the commits, but my IDE went in crazy mode. :)

**Pull request closed without merging**
